### ISSUE TITLE
Examples differ on pins for SonicIO

### ISSUE THREAD

**Issue by jr-air** [m5stack/M5Unit-Sonic#3]
The pins used in the examples for the SonicIO unit, diff between the Stick(s) and Core(s) models.

 In example "Unit_SonicIO_M5StickC.ino", pins are re-pointed to G32/G33.
For "Unit_SonicIO_M5Core2.ino", the default pins are configured instead, which does work but keeps me from using PortA.

Should the Core(s) version also have there pins re-mapped?

**Comment by TinyuZhao** [comment]
SonicIO is the use of GPIO to control the device, Core device GPIO control port is PortB, you need to match the [Bottom2](https://docs.m5stack.com/en/base/m5go_bottom2) base to pin out the corresponding GPIO, of course, you can also change to PortA, both can be used
